baseURL = "https://superluminar.io/"
languageCode = "en-us"
title = "superluminar GmbH"
theme = "superluminar"
sectionPagesMenu = "main"
disqusShortname = "superluminar"

[blackfriday]
extensions = ["hardLineBreak"]

[params]
gaTrackingId = "UA-110302159-1"

[permalinks]
post = "/:year/:month/:day/:title/"
