baseURL = "https://superluminar.io/"
languageCode = "en-us"
title = "superluminar GmbH i.G."
theme = "superluminar"
sectionPagesMenu = "main"

[blackfriday]
extensions = ["hardLineBreak"]

[params]
gaTrackingId = "UA-110302159-1"
